### ISSUE TITLE
org.bouncycastle.tls.TlsFatalAlertReceived: handshake_failure

### ISSUE THREAD

**Issue by TheBestOrNothing** [TheBestOrNothing/whispeer-kafka-oauth#4]
Sep 05, 2023 12:21:03 PM org.bouncycastle.jsse.provider.ProvTlsClient notifyAlertReceived
 INFO: [client #44 @2181a2c6] received fatal(2) handshake_failure(40) alert
 Sep 05, 2023 12:21:03 PM org.bouncycastle.jsse.provider.ProvTlsClient notifyConnectionClosed
 INFO: [client #44 @2181a2c6] disconnected from eth-goerli.g.alchemy.com:443
 Sep 05, 2023 12:21:03 PM org.bouncycastle.jsse.provider.ProvTlsClient notifyHandshakeBeginning
 INFO: [client #45 @4df04033] opening connection to eth-goerli.g.alchemy.com:443
Sep 05, 2023 12:21:03 PM org.bouncycastle.jsse.provider.ProvTlsClient notifyAlertReceived
 INFO: [client #45 @4df04033] received fatal(2) handshake_failure(40) alert
Sep 05, 2023 12:21:03 PM org.bouncycastle.jsse.provider.ProvTlsClient notifyConnectionClosed
 INFO: [client #45 @4df04033] disconnected from eth-goerli.g.alchemy.com:443
org.bouncycastle.tls.TlsFatalAlertReceived: handshake_failure(40)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at org.bouncycastle.tls.TlsProtocol.handleAlertMessage(TlsProtocol.java:245)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at org.bouncycastle.tls.TlsProtocol.processAlertQueue(TlsProtocol.java:740)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at org.bouncycastle.tls.TlsProtocol.processRecord(TlsProtocol.java:563)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at org.bouncycastle.tls.RecordStream.readRecord(RecordStream.java:247)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at org.bouncycastle.tls.TlsProtocol.safeReadRecord(TlsProtocol.java:879)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at org.bouncycastle.tls.TlsProtocol.blockForHandshake(TlsProtocol.java:427)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at org.bouncycastle.tls.TlsClientProtocol.connect(TlsClientProtocol.java:88)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at org.bouncycastle.jsse.provider.ProvSSLSocketWrap.startHandshake(ProvSSLSocketWrap.java:608)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at org.bouncycastle.jsse.provider.ProvSSLSocketWrap.startHandshake(ProvSSLSocketWrap.java:584)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.kt:379)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.kt:337)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:209)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:226)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at org.web3j.protocol.http.HttpService.performIO(HttpService.java:159)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at org.web3j.protocol.Service.send(Service.java:48)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at org.web3j.protocol.core.Request.send(Request.java:87)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at io.strimzi.kafka.oauth.validator.AccessValidator.ethValidate(AccessValidator.java:109)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at io.strimzi.kafka.oauth.server.JaasServerOauthValidatorCallbackHandler.handleCallback (JaasServerOauthValidatorCallbackHandler.java:343)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at io.strimzi.kafka.oauth.server.JaasServerOauthValidatorCallbackHandler.delegatedHandle (JaasServerOauthValidatorCallbackHandler.java:322)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at io.strimzi.kafka.oauth.server.JaasServerOauthValidatorCallbackHandler.handle(JaasServerOauthValidatorCallbackHandler.java:301)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at org.apache.kafka.common.security.oauthbearer.internals.OAuthBearerSaslServer.process(OAuthBearerSaslServer.java:156)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at org.apache.kafka.common.security.oauthbearer.internals.OAuthBearerSaslServer.evaluateResponse (OAuthBearerSaslServer.java:101)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at org.apache.kafka.common.security.authenticator.SaslServerAuthenticator.handleSaslToken(SaslServerAuthenticator.java:459)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at org.apache.kafka.common.security.authenticator.SaslServerAuthenticator.authenticate(SaslServerAuthenticator.java:288)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at org.apache.kafka.common.network.KafkaChannel.prepare(KafkaChannel.java:181)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at org.apache.kafka.common.network.Selector.pollSelectionKeys(Selector.java:543)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at org.apache.kafka.common.network.Selector.poll(Selector.java:481)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at kafka.network.Processor.poll(SocketServer.scala:1056)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at kafka.network.Processor.run(SocketServer.scala:960)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at java.base/java.lang.Thread.run(Thread.java:833)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Suppressed: org.bouncycastle.tls.TlsFatalAlertReceived: handshake_failure(40)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;... 43 more

**Comment by TheBestOrNothing** [comment]
handshake failed when the we3j use  org.bouncycastle.jsse.provider to handsake. The failure happened when kafka broker start on docker container, but it is successful to runing on the host. Maybe the failure is related to the network configuration in the docker conainer. Maybe the failure reason is  the time from org.bouncycastle.jsse.provider is not same as system's in container.

**Comment by TheBestOrNothing** [comment]
The workround is to adapt the code web3j.ethCall to AsyncHttpClient.

### Orignal web3j.ethCall code:
```
        Web3j web3j = Web3j.build(new HttpService(provider)); 
        Function function = new Function(
                "getExpirationTime",
                Collections.singletonList(new Address(address)), // Function parameters

        String encodedFunction = FunctionEncoder.encode(function);

        //from = admin; to = whispeerAddress; data = encodedFunction;
        Transaction transaction = new Transaction(adminAdress, null, null, null, whispeerAdress, null, encodedFunction, null, null, null);

        EthCall response = null;
        try {
            response = web3j.ethCall(transaction, DefaultBlockParameterName.LATEST).send();
        } catch (IOException e) {
            e.printStackTrace();
        }
``` 

### the workwroud code with AsyncHttpClient :
```
        String body = null;
        AsyncHttpClient client = new DefaultAsyncHttpClient();

        // Create the innermost JSON object
        JSONObject innerObject = new JSONObject();
        innerObject.put("to", whispeerAdress);
        innerObject.put("from", adminAdress);
        innerObject.put("data", encodedFunction);

        // Create the JSON array for "params" and add the inner object and the string
        JSONArray paramsArray = new JSONArray();
        paramsArray.put(innerObject);
        paramsArray.put("latest");

        // Create the outer JSON object
        JSONObject jsonObject = new JSONObject();
        jsonObject.put("id", 1);
        jsonObject.put("jsonrpc", "2.0");
        jsonObject.put("method", "eth_call");
        jsonObject.put("params", paramsArray);

        body = jsonObject.toString();
        System.out.println(jsonObject.toString());

        try {

            Response response = client.prepare("POST", provider)
                      .setHeader("accept", "application/json")
                      .setHeader("content-type", "application/json")
                      .setBody(body)
                      .execute()
                      .toCompletableFuture()
                      .join();

            if (response.getStatusCode() == 200) {
                String responseStr = response.getResponseBody();
                System.out.println("Response: " + responseStr);
                status = true;

                // Parse the JSON response using org.json.JSONObject
                JSONObject responseJson = new JSONObject(responseStr);

                // Get the "result" value as a hexadecimal string
                String resultHex = responseJson.getString("result");

                // Convert the hexadecimal string to a BigInteger
                expirationTime = new BigInteger(resultHex.substring(2), 16);
            }

        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            try {
                client.close();
            } catch (IOException e) {
                // TODO Auto-generated catch block
                e.printStackTrace();
            }
        }
```
